# sabnzbd:
#   container_name: sabnzbd
#   image: ghcr.io/hotio/sabnzbd
#   restart: unless-stopped
#   logging:
#     driver: json-file
#   environment:
#     - PUID=1000
#     - PGID=1000
#     - TZ=Europe/Amsterdam
#   ports:
#     - 8080:8080
#     - 9090:9090
#   volumes:
#     - /etc/localtime:/etc/localtime:ro
#     - ~/services/jellyfin/sabnzbd:/config
#     - ~/services/jellyfin/data/usenet:/data/usenet:rw

# teslamate:
#   container_name: teslamate
#   image: teslamate/teslamate
#   restart: unless-stopped
#   environment:
#     - ENCRYPTION_KEY=secretkey #replace with a secure key to encrypt your Tesla API tokens
#     - DATABASE_USER=teslamate
#     - DATABASE_PASS=password #insert your secure database password!
#     - DATABASE_NAME=teslamate
#     - DATABASE_HOST=database
#     - MQTT_HOST=mosquitto
#   ports:
#     - 4000:4000
#   volumes:
#     - ~/services/teslamate/import:/opt/app/import
#   cap_drop:
#     - all

# teslamate_database:
#   container_name: teslamate_database
#   image: postgres:16
#   restart: unless-stopped
#   environment:
#     - POSTGRES_USER=teslamate
#     - POSTGRES_PASSWORD=password #insert your secure database password!
#     - POSTGRES_DB=teslamate
#   volumes:
#     - ~/services/teslamate/db:/var/lib/postgresql/data

# teslamate_grafana:
#   container_name: teslamate_grafana
#   image: teslamate/grafana
#   restart: unless-stopped
#   environment:
#     - DATABASE_USER=teslamate
#     - DATABASE_PASS=password #insert your secure database password!
#     - DATABASE_NAME=teslamate
#     - DATABASE_HOST=database
#   ports:
#     - 3000:3000
#   volumes:
#     - ~/services/teslamate/grafana:/var/lib/grafana

# teslamate_mosquitto:
#   container_name: teslamate_mosquitto
#   image: eclipse-mosquitto:2
#   restart: unless-stopped
#   command: mosquitto -c /mosquitto-no-auth.conf
#   # ports:
#   #   - 1883:1883
#   volumes:
#     - ~/services/teslamate/mosquitto/conf:/mosquitto/config
#     - ~/services/teslamate/mosquitto/data:/mosquitto/data
