version: "3.8"
services:
  stremio:
    build: .
    container_name: stremio
    volumes:
      - /root/services/stremio:/stremio/config
    restart: unless-stopped
    ports:
      - 11470:11470
    environment:
      - NO_CORS=1
      - APP_PATH=/stremio/config
    networks:
      - network_default
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "26"
      - "303"
networks:
  network_default:
    external: true
